{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a70125d5-19e4-4488-91d3-71a43799e3fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import ttk, filedialog, messagebox\n",
    "import pandas as pd\n",
    "from io import StringIO\n",
    "from pyproj import Proj, transform\n",
    "\n",
    "\n",
    "class UTMConverterApp:\n",
    "    def __init__(self, master):\n",
    "        self.master = master\n",
    "        master.title(\"Advanced Coordinate Converter\")\n",
    "        master.geometry(\"750x500\")\n",
    "        master.resizable(False, False)\n",
    "\n",
    "        # ========== FRAME INPUT ==========\n",
    "        frame_input = ttk.LabelFrame(master, text=\"Input Parameters\")\n",
    "        frame_input.pack(padx=10, pady=10, fill=\"x\")\n",
    "\n",
    "        # Conversion Mode (hanya 1 mode aktif: UTM ke LatLon)\n",
    "        ttk.Label(frame_input, text=\"Conversion Mode:\").grid(row=0, column=0, sticky=\"w\", padx=5, pady=5)\n",
    "        self.mode = ttk.Combobox(frame_input, values=[\"UTM to LatLon (Decimal)\"], state=\"readonly\", width=25)\n",
    "        self.mode.current(0)\n",
    "        self.mode.grid(row=0, column=1, padx=5, pady=5)\n",
    "\n",
    "        # Zone\n",
    "        ttk.Label(frame_input, text=\"UTM Zone:\").grid(row=1, column=0, sticky=\"w\", padx=5, pady=5)\n",
    "        self.zone_entry = ttk.Entry(frame_input, width=10)\n",
    "        self.zone_entry.insert(0, \"49\")\n",
    "        self.zone_entry.grid(row=1, column=1, sticky=\"w\", padx=5, pady=5)\n",
    "\n",
    "        # Hemisphere\n",
    "        ttk.Label(frame_input, text=\"Hemisphere:\").grid(row=2, column=0, sticky=\"w\", padx=5, pady=5)\n",
    "        self.hemisphere = ttk.Combobox(frame_input, values=[\"Northern Hemisphere (N)\", \"Southern Hemisphere (S)\"], state=\"readonly\", width=25)\n",
    "        self.hemisphere.current(1)\n",
    "        self.hemisphere.grid(row=2, column=1, padx=5, pady=5)\n",
    "\n",
    "        # CSV Data Textbox\n",
    "        ttk.Label(frame_input, text=\"Paste CSV Data (Name, X, Y):\").grid(row=3, column=0, sticky=\"nw\", padx=5, pady=5)\n",
    "        self.csv_text = tk.Text(frame_input, width=60, height=6)\n",
    "        self.csv_text.insert(tk.END, \"Nama,X,Y\\na1,533000,9100000\\na2,535000,9100000\\na3,538500,9100000\")\n",
    "        self.csv_text.grid(row=3, column=1, padx=5, pady=5)\n",
    "\n",
    "        # Convert Button\n",
    "        self.convert_button = ttk.Button(frame_input, text=\"Convert Coordinates\", command=self.convert_coordinates)\n",
    "        self.convert_button.grid(row=4, column=1, pady=10, sticky=\"e\")\n",
    "\n",
    "        # ========== FRAME OUTPUT ==========\n",
    "        frame_output = ttk.LabelFrame(master, text=\"Results\")\n",
    "        frame_output.pack(padx=10, pady=10, fill=\"both\", expand=True)\n",
    "\n",
    "        # Treeview untuk menampilkan hasil\n",
    "        self.tree = ttk.Treeview(frame_output, columns=(\"Nama\", \"Latitude\", \"Longitude\"), show=\"headings\")\n",
    "        self.tree.heading(\"Nama\", text=\"Nama\")\n",
    "        self.tree.heading(\"Latitude\", text=\"Latitude\")\n",
    "        self.tree.heading(\"Longitude\", text=\"Longitude\")\n",
    "        self.tree.column(\"Nama\", width=100)\n",
    "        self.tree.column(\"Latitude\", width=150)\n",
    "        self.tree.column(\"Longitude\", width=150)\n",
    "        self.tree.pack(fill=\"both\", expand=True, pady=5, padx=5)\n",
    "\n",
    "        # Tombol download CSV\n",
    "        self.save_button = ttk.Button(frame_output, text=\"Download CSV\", command=self.save_csv)\n",
    "        self.save_button.pack(pady=5, anchor=\"e\")\n",
    "\n",
    "        # Variabel penyimpanan hasil\n",
    "        self.result_df = None\n",
    "\n",
    "\n",
    "    def utm_to_latlon(self, easting, northing, zone_number, southern_hemisphere=False):\n",
    "        \"\"\"\n",
    "        Mengonversi koordinat UTM ke Latitude dan Longitude.\n",
    "        \"\"\"\n",
    "        utm_proj = Proj(proj='utm', zone=zone_number, ellps='WGS84', south=southern_hemisphere)\n",
    "        wgs84_proj = Proj(proj='latlong', datum='WGS84')\n",
    "        lon, lat = transform(utm_proj, wgs84_proj, easting, northing)\n",
    "        return lat, lon\n",
    "\n",
    "\n",
    "    def convert_coordinates(self):\n",
    "        \"\"\"\n",
    "        Membaca data dari textbox, konversi UTM → LatLon, dan tampilkan di tabel.\n",
    "        \"\"\"\n",
    "        try:\n",
    "            csv_data = self.csv_text.get(\"1.0\", tk.END).strip()\n",
    "            df = pd.read_csv(pd.compat.StringIO(csv_data))\n",
    "\n",
    "            zone = int(self.zone_entry.get())\n",
    "            southern = \"Southern\" in self.hemisphere.get()\n",
    "\n",
    "            df[['Latitude', 'Longitude']] = df.apply(\n",
    "                lambda row: self.utm_to_latlon(row['X'], row['Y'], zone, southern),\n",
    "                axis=1, result_type='expand'\n",
    "            )\n",
    "\n",
    "            # Tampilkan hasil di Treeview\n",
    "            for row in self.tree.get_children():\n",
    "                self.tree.delete(row)\n",
    "\n",
    "            for _, r in df.iterrows():\n",
    "                self.tree.insert(\"\", \"end\", values=(r['Nama'], round(r['Latitude'], 6), round(r['Longitude'], 6)))\n",
    "\n",
    "            messagebox.showinfo(\"Success\", f\"Successfully converted {len(df)} points.\")\n",
    "            self.result_df = df\n",
    "\n",
    "        except Exception as e:\n",
    "            messagebox.showerror(\"Error\", f\"Gagal mengonversi data.\\n{e}\")\n",
    "\n",
    "\n",
    "    def save_csv(self):\n",
    "        \"\"\"\n",
    "        Menyimpan hasil konversi ke file CSV.\n",
    "        \"\"\"\n",
    "        if self.result_df is None:\n",
    "            messagebox.showwarning(\"No Data\", \"Tidak ada hasil untuk disimpan.\")\n",
    "            return\n",
    "\n",
    "        filepath = filedialog.asksaveasfilename(defaultextension=\".csv\", filetypes=[(\"CSV Files\", \"*.csv\")])\n",
    "        if filepath:\n",
    "            self.result_df.to_csv(filepath, index=False)\n",
    "            messagebox.showinfo(\"Saved\", f\"Hasil disimpan di:\\n{filepath}\")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# MAIN PROGRAM\n",
    "# ============================================================\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = UTMConverterApp(root)\n",
    "    root.mainloop()\n",
    "import io  # <--- tambahkan ini di atas file\n",
    "\n",
    "def convert_coordinates(self):\n",
    "    \"\"\"\n",
    "    Membaca data dari textbox, konversi UTM → LatLon, dan tampilkan di tabel.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        csv_data = self.csv_text.get(\"1.0\", tk.END).strip()\n",
    "        # gunakan io.StringIO, bukan pd.compat.StringIO\n",
    "        df = pd.read_csv(io.StringIO(csv_data))\n",
    "\n",
    "        zone = int(self.zone_entry.get())\n",
    "        southern = \"Southern\" in self.hemisphere.get()\n",
    "\n",
    "        df[['Latitude', 'Longitude']] = df.apply(\n",
    "            lambda row: self.utm_to_latlon(row['X'], row['Y'], zone, southern),\n",
    "            axis=1, result_type='expand'\n",
    "        )\n",
    "\n",
    "        # Tampilkan hasil di Treeview\n",
    "        for row in self.tree.get_children():\n",
    "            self.tree.delete(row)\n",
    "\n",
    "        for _, r in df.iterrows():\n",
    "            self.tree.insert(\"\", \"end\", values=(r['Nama'], round(r['Latitude'], 6), round(r['Longitude'], 6)))\n",
    "\n",
    "        messagebox.showinfo(\"Success\", f\"Successfully converted {len(df)} points.\")\n",
    "        self.result_df = df\n",
    "\n",
    "    except Exception as e:\n",
    "        messagebox.showerror(\"Error\", f\"Gagal mengonversi data.\\n{e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6e2e60b8-f384-4753-8b07-c45e6f5e069e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyproj in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (3.7.2)\n",
      "Requirement already satisfied: certifi in c:\\users\\lenovo\\anaconda3\\lib\\site-packages (from pyproj) (2025.8.3)\n"
     ]
    }
   ],
   "source": [
    "!pip install pyproj"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8efb255-96a9-4352-a264-0323d0f0a81f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
